env:
  es6: true
  browser: true
extends:
  - 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    - jsx: true
rules:
  indent:
    - warn
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  "no-unused-vars":
    - 0
  "no-console": 0
